### ISSUE TITLE
Project name is a misnomer?

### ISSUE THREAD

**Issue by miclgael** [Fooxly/workspace#11]
Hi there, 

Thanks for this great extension, I use it daily!

However, I have to question the title of the extension. Doesn't this add confusion against [VS Code's built-in workspaces feature](https://code.visualstudio.com/docs/editor/workspaces)? 

Would you be open to adopting a more descriptive name like "Hide Files" or even "Tidy Workspace" ?

Cheers
MG

**Comment by thom1606** [comment]
Hey there, thank you for taking out time of your day to take a look at our package, but we are currently not interested in changing the name of the extension as this will never be correctly alongside the actual vscode workspace functionality.

**Comment by miclgael** [comment]
Thanks for your speedy reply @thom1606 - I'm just suggesting the extension is very difficult to find by keyword currently.
