### ISSUE TITLE
Unable to view hidden files, no examples in README

### ISSUE THREAD

**Issue by bdrelling** [Fooxly/workspace#13]
It's not obvious how to do the following, the README is missing instructions for:

> - View your hidden files
> - Bring back a hidden file or folder

**Comment by thom1606** [comment]
Hey there, if you press the statusbar button we added on the bottom right, the files you hid will be showed.

For the bringing back files:
1. Make sure you have the hidden files visible.
2. Right click on a specific folder / file you have hidden and select the toggle option we added.

Doing this should toggle your file from hidden to visible, you can always check the .vscode/settings.json to verify everything is setup correctly. We make use of the build in files.exclude from VSCode.

But we will take a look at updating the documentation soon to try and better communicate this to our users.

**Comment by thom1606** [comment]
Quick update, we have updated the texts and it should hopefully better resemble the functionality.
