### ISSUE TITLE
Shared folders across multiple workspaces causes weird and confusing behavior

### ISSUE THREAD

**Issue by natefabian18** [Fooxly/workspace#14]
# Steps to reproduce
- Have two vscode workspaces open, both of which have a different primary folder (where the vscode settings.json is stored). 
- Have a secondary folder that is shared between the two workspaces. 
- Showing hidden files in either workspace causes the hidden files to always be shown as long as both workspaces are open

# Expected Behavior
Hidden files should be isolated to workspaces even if that workspace shares folders with other workspaces or hide/show files should be global to the system

# Theory
It seems that the two workspaces fight over what the state should be as when workspace A tries to hide the files workspace B chimes in that its config says they should be shown which causes workspace A to hide them for a second then show them again.

![image](https://github.com/Fooxly/workspace/assets/10154708/52d4bbdc-3e12-4c5b-9442-7c0b4742681b)
In this configuration you can never hide any files until you close one of the two workspaces

PS. Love the extension, Thank you

**Comment by thom1606** [comment]
Hey there, we have recently been hard at work with updated the Workspace extension which should improve your experience with this.
