### ISSUE TITLE
VS Code Workspace support?

### ISSUE THREAD

**Issue by cris7ea** [Fooxly/workspace#5]
Are there any plans to support VS Code [multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces) in the future?

I like the extension and understand the functionality for single projects, works great! It's just that when you try to use it in a workspace it doesn't hide the folders/files.

Thanks in advance.

**Comment by thom1606** [comment]
Thanks for pointing out that it doesn't work with Multi-root Workspaces. We'll see if we can improve support for the extension in this area.

**Comment by cris7ea** [comment]
By way, I recently found out that when you add `.vscode/settings.json` in the root of my workspace and put your settings in there, it works.
